name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Fix permissions
        run: chmod -R 755 node_modules/.bin

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test
